dist: xenial
language: php
php:
- '7.4snapshot'
- '7.3'
- '7.2'
- '7.1'
- '7.0'
- '5.6'

before_install:
- echo "phar.readonly = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
- tests/makephar.sh
