dist: xenial
language: php
php:
- '7.4'
- '7.0'
- '5.6'


jobs:
  allow_failures:
  - php: '5.6'

before_install:
- echo "phar.readonly = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- tests/waitPackagist.php

script:
- tests/makephar.sh
