name: build
on: [create]
jobs:
  run:
    runs-on: daniil-proliant
    strategy:
      matrix:
        php:
          - '8.0'
          - '7.4'
          - '7.3'
          - '7.2'
          - '7.1'
          - '7.0'
    name: PHP ${{ matrix.php }} build
    env:
      PHP_CS_FIXER_IGNORE_ENV: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, sockets, gmp, curl, xml, json
          coverage: none
          ini-values: phar.readonly=0

      - name: Wait for packagist
        run: |
          tests/waitPackagist.php

      - name: Build
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TOKEN: ${{ secrets.BOT_TOKEN }}
          DEST: ${{ secrets.DEST }}
          DESTINATIONS: ${{ secrets.DESTINATIONS }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          tests/makephar.sh
